#pragma once

//From glfw3.h

#define DD_INPUT_MOUSE_BUTTON_1         0
#define DD_INPUT_MOUSE_BUTTON_2         1
#define DD_INPUT_MOUSE_BUTTON_3         2
#define DD_INPUT_MOUSE_BUTTON_4         3
#define DD_INPUT_MOUSE_BUTTON_5         4
#define DD_INPUT_MOUSE_BUTTON_6         5
#define DD_INPUT_MOUSE_BUTTON_7         6
#define DD_INPUT_MOUSE_BUTTON_8         7
#define DD_INPUT_MOUSE_BUTTON_LAST      DD_INPUT_MOUSE_BUTTON_8
#define DD_INPUT_MOUSE_BUTTON_LEFT      DD_INPUT_MOUSE_BUTTON_1
#define DD_INPUT_MOUSE_BUTTON_RIGHT     DD_INPUT_MOUSE_BUTTON_2
#define DD_INPUT_MOUSE_BUTTON_MIDDLE    DD_INPUT_MOUSE_BUTTON_3